# Generated by Django 4.2 on 2023-04-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='hashedPassword',
            field=models.BinaryField(),
        ),
    ]
